# Generated by Django 5.2 on 2025-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
