services:
  - type: web
    name: stage222-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
