# Generated by Django 5.2 on 2025-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(default='3 months', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='fixed_pay_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='fixed_pay_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='incentives_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='incentives_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='opportunity_type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='internship', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='perks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='internship',
            name='preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='internship',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in-office', 'In-office')], default='remote', max_length=20),
        ),
    ]
