# Generated by Django 5.2 on 2025-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_alternate_phone_internship_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='fixed_pay_max',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='fixed_pay_min',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='incentives_max',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='incentives_min',
        ),
        migrations.AddField(
            model_name='internship',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
