# Generated by Django 5.2 on 2025-06-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_remove_internship_fixed_pay_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='alternate_phone',
        ),
    ]
