# Generated by Django 5.2 on 2025-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_remove_internship_alternate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
