# Generated by Django 5.2.1 on 2025-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
