# Generated by Django 5.2.1 on 2025-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_recruiterprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(help_text='Phone number must start with 2, 3, or 4 and be 8 digits long', max_length=20, unique=True),
        ),
    ]
