# Generated by Django 5.2 on 2025-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_alter_recruiterprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
