# Generated by Django 5.2.1 on 2025-06-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='employee_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='org_licenses/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
