# Generated by Django 5.2.1 on 2025-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_about_organization_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, choices=[('Nouakchott', 'Nouakchott'), ('Nouadhibou', 'Nouadhibou'), ('Aïoun', 'Aïoun'), ('Akjoujt', 'Akjoujt'), ('Aleg', 'Aleg'), ('Atar', 'Atar'), ('Kaédi', 'Kaédi'), ('Kiffa', 'Kiffa'), ('Néma', 'Néma'), ('Rosso', 'Rosso'), ('Sélibabi', 'Sélibabi'), ('Tidjikdja', 'Tidjikdja'), ('Zouerate', 'Zouerate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employee_range',
            field=models.CharField(blank=True, choices=[('0–1', '0–1'), ('2–10', '2–10'), ('11–50', '11–50'), ('51–200', '51–200'), ('201–500', '201–500'), ('501–1000', '501–1000'), ('1001–5000', '1001–5000'), ('5000+', '5000+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('Advertising/Marketing', 'Advertising/Marketing'), ('Agriculture/Dairy', 'Agriculture/Dairy'), ('Animation', 'Animation'), ('Architecture/Interior Design', 'Architecture/Interior Design'), ('Automobile', 'Automobile'), ('BPO', 'BPO'), ('Biotechnology', 'Biotechnology'), ('Consulting', 'Consulting'), ('Data Science/AI', 'Data Science/AI'), ('Design/UX', 'Design/UX'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Finance', 'Finance'), ('Government/Public Sector', 'Government/Public Sector'), ('Healthcare', 'Healthcare'), ('HR/Recruitment', 'HR/Recruitment'), ('IT/Software', 'IT/Software'), ('Legal', 'Legal'), ('Logistics/Supply Chain', 'Logistics/Supply Chain'), ('Manufacturing', 'Manufacturing'), ('Media/Journalism', 'Media/Journalism'), ('NGO / Non-Profit', 'NGO / Non-Profit'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Travel & Tourism', 'Travel & Tourism'), ('Other', 'Other')], max_length=255),
        ),
    ]
