# Generated by Django 5.2 on 2025-07-01 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 1, 11, 44, 59, 414411, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
