# Generated by Django 5.2.1 on 2025-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_options_alter_emailotp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
