# Generated by Django 5.2 on 2025-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
