# Generated by Django 5.2 on 2025-07-02 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Nouakchott', 'Nouakchott'), ('Nouadhibou', 'Nouadhibou'), ('Zouerate', 'Zouerate'), ('Rosso', 'Rosso'), ('Kiffa', 'Kiffa'), ('Atar', 'Atar'), ('Aleg', 'Aleg'), ('Tidjikja', 'Tidjikja'), ('Kaedi', 'Kaédi'), ('Néma', 'Néma'), ('Selibaby', 'Sélibaby')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(help_text='Must be a valid Mauritanian number: +2222, +2223, or +2224 prefix', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid Mauritanian number starting with +2222, +2223, or +2224.', regex='^\\+222[234]\\d{7}$')]),
        ),
    ]
